const state={tipo:'estudiante',estado:'INGRESO',qr:null,camara:false};
function mostrarVista(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));if(id!=='registro')detenerCamara();window.scrollTo(0,0)}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>mostrarVista(b.dataset.view)));
homeBtn.addEventListener('click',()=>mostrarVista('portal'));salirBtn.addEventListener('click',()=>mostrarVista('portal'));
entrarBtn.addEventListener('click',()=>{const m=loginMsg;if(!usuario.value.trim()||!password.value.trim()){m.textContent='Ingrese usuario y contraseña.';return}m.textContent='Acceso de prueba V2. La autenticación real se conectará al backend.';mostrarVista('panel')});
document.querySelectorAll('[data-tipo]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-tipo]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.tipo=b.dataset.tipo}));
document.querySelectorAll('[data-estado]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-estado]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.estado=b.dataset.estado}));
async function iniciarCamara(){const m=camMsg;if(!window.isSecureContext){m.textContent='La cámara requiere HTTPS.';return}if(!navigator.mediaDevices?.getUserMedia){m.textContent='Este navegador no permite acceso a cámara.';return}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});stream.getTracks().forEach(t=>t.stop());if(typeof Html5QrcodeScanner==='undefined'){m.textContent='Cámara disponible, pero no se cargó el lector QR.';return}state.qr=new Html5QrcodeScanner('reader',{fps:10,qrbox:{width:240,height:240},rememberLastUsedCamera:true},false);state.qr.render(texto=>{detenerCamara();regMsg.textContent='QR leído: '+texto+'. Validación del ID MGP pendiente.'},()=>{});state.camara=true;m.textContent='📷 Cámara activa. Apunte al QR del carnet.'}catch(e){m.textContent='❌ Cámara rechazada: '+e.name+' — '+e.message;console.error(e)}}
async function detenerCamara(){if(state.qr){try{await state.qr.clear()}catch(e){}}state.qr=null;state.camara=false;if(camMsg)camMsg.textContent='Cámara detenida'}
camBtn.addEventListener('click',iniciarCamara);stopCamBtn.addEventListener('click',detenerCamara);
consultarBtn.addEventListener('click',()=>{consultaMsg.textContent=dniConsulta.value.trim()&&claveConsulta.value.trim()?'Consulta frontend lista para conectarse al backend.':'Ingrese DNI y código de consulta.'});
dniBtn.addEventListener('click',()=>{regMsg.textContent=dniManual.value.trim()?'Registro DNI preparado para backend.':'Ingrese el DNI.'});
